FROM rust:1.84-alpine AS build
WORKDIR /build

ENV SQLX_OFFLINE=true

##
## -------------build backend-------------------------
##

RUN apk update && apk add git alpine-sdk make libffi-dev openssl-dev pkgconfig bash postgresql

COPY backend/Cargo.lock backend/Cargo.toml .
COPY backend/.sqlx .sqlx

RUN mkdir src
RUN echo "pub fn test() {}" > src/lib.rs

RUN cargo build --locked

RUN rm -r src

EXPOSE 8080

COPY backend/src src
CMD ["cargo", "run"]
