/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/container": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_container"];
        delete: operations["destroy_container"];
        options?: never;
        head?: never;
        patch: operations["change_container"];
        trace?: never;
    };
    "/api/container/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["move_container"];
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_due"];
        put?: never;
        post: operations["take_stock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_item"];
        put: operations["change_stored_item"];
        post: operations["create_item"];
        delete: operations["delete_item"];
        options?: never;
        head?: never;
        patch: operations["change_item"];
        trace?: never;
    };
    "/api/item/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["move_item"];
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_shipment"];
        put?: never;
        post: operations["create"];
        delete: operations["destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shortage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_shortage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_storage"];
        delete: operations["destroy_storage"];
        options?: never;
        head?: never;
        patch: operations["change_storage"];
        trace?: never;
    };
    "/api/storages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_storages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storages/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_storage_container_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storages/containers/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_container_item_tree_for_storage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_suppliers"];
        put?: never;
        post: operations["create_supplier"];
        delete: operations["delete_supplier"];
        options?: never;
        head?: never;
        patch: operations["update_supplier"];
        trace?: never;
    };
    "/api/supply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["supply_item"];
        delete: operations["unsupply_item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Basic item information */
        BasicItem: {
            /**
             * Format: float
             * @description The current total amount of the item accros all storages
             */
            amount?: number | null;
            /** @description The items name */
            name: string;
            /** @description List of storage locations containing the item with basic info */
            storage?: components["schemas"]["BasicItemStorage"][] | null;
            /** @description The unit the amount is counted in */
            unit: string;
        };
        /** @description Basic info about where an item is stored */
        BasicItemStorage: {
            /** @description The container where the item is stored */
            container: string;
            /** @description The state the item is in (if more is needed to ordered) */
            state: components["schemas"]["OrderState"];
            /** @description The storage where the item is stored */
            storage: string;
        };
        /** @description Info used to create a container */
        ContainerCreateRequest: {
            inventory_interval?: null | components["schemas"]["Interval"];
            /** @description The containers name */
            name: string;
            /** @description The storage location the container is at */
            storage: string;
        };
        /** @description List of containers with items */
        ContainerItem: {
            /** @description List of items */
            items: components["schemas"]["MinimalItem"][];
            /** @description The containers name */
            name: string;
        };
        /** @description Info used to move a container */
        ContainerMoveRequest: {
            /** @description The name of the storage the container is moved from */
            from_storage: string;
            /** @description Spcifies if containers with the same name should be merged */
            merge: boolean;
            /** @description The containers name */
            name: string;
            /** @description The name of the storage the container is moved to */
            to_storage: string;
        };
        /** @description List of containers at a storage location */
        ContainerStorage: {
            /** @description List of containers */
            containers?: string[] | null;
            /** @description The storages name */
            name: string;
        };
        /** @description Info used to update a container */
        ContainerUpdateRequest: {
            /** @description The containers name */
            name: string;
            /** @description The containers new name if it should be changed */
            new_name?: string | null;
            /** @description The storage location the container should be at */
            storage: string;
        };
        /** @description Detailed item infarmation */
        DetailedItem: {
            /**
             * Format: float
             * @description The avrage weekly consumption over the last mounth
             */
            avrage_consuption?: number | null;
            inventory_interval?: null | components["schemas"]["Interval"];
            /** @description The items name */
            name: string;
            /** @description The storages that this item type is stored in */
            storage?: components["schemas"]["StorageListing"][] | null;
            /** @description The suppliers that the item is bought from */
            supplier?: components["schemas"]["SupplierListing"][] | null;
            /** @description The unit every amount is counted in */
            unit: string;
        };
        DueContainer: {
            items: components["schemas"]["DueItem"][];
            name: string;
        };
        /** @description An item due to be inventoried */
        DueItem: {
            /** Format: float */
            amount: number;
            name: string;
            /** @description The unit that the amount is measured in */
            unit?: string | null;
        };
        DueStorage: {
            containers?: components["schemas"]["DueContainer"][] | null;
            name: string;
        };
        Group: string;
        HivePermission: {
            id: string;
            scope?: string | null;
        };
        /** Format: duration */
        Interval: string;
        /** @description Info to add an item to storage */
        ItemAddRequest: {
            /**
             * Format: float
             * @description The number of items currently in storage
             */
            amount: number;
            /** @description The container the item is stored in, can be "default" (loose) */
            container: string;
            inventory_interval?: null | components["schemas"]["Interval"];
            /**
             * Format: float
             * @description The upper limit on the number of items (order ceiling)
             */
            max?: number | null;
            /**
             * Format: float
             * @description The lower limit on how many items should be in storage (order limit)
             */
            min?: number | null;
            /** @description The items name */
            name: string;
            /** @description The storage location the item is at */
            storage: string;
            /** @description The unit in which amount is counted (st, 6-pack, %, etc) */
            unit?: string | null;
        };
        /** @description Info to change the name of an item (accross all storages) */
        ItemChangeNameRequest: {
            inventory_interval?: null | components["schemas"]["Interval"];
            /** @description The name to change from */
            name: string;
            /** @description The name to change to */
            new_name?: string | null;
            /** @description The unit amount is counted in */
            unit: string;
        };
        /** @description Info used to move an item */
        ItemMoveRequest: {
            /** @description The name of the container the items is moved from */
            from_container: string;
            /** @description The name of the storage the items is moved from */
            from_storage: string;
            /** @description The items name */
            name: string;
            /** @description The name of the container the items is moved to */
            to_container: string;
            /** @description The name of the storage the items is moved to */
            to_storage: string;
        };
        Log: (components["schemas"]["StateLog"] & {
            /** @enum {string} */
            type: "state";
        }) | (components["schemas"]["MoveLog"] & {
            /** @enum {string} */
            type: "move";
        });
        /** @description An item ment to be viewed in the context of a tree representation of the db */
        MinimalItem: {
            /**
             * Format: float
             * @description The current amount
             */
            amount: number;
            /** @description The items name */
            name: string;
            /**
             * Format: date-time
             * @description The next date when the item needs to be inventoried
             */
            next_inventory?: string | null;
            state?: null | components["schemas"]["OrderState"];
            /** @description The unit current is counted in */
            unit: string;
        };
        MoveLog: {
            /** Format: float */
            amount: number;
            from_container: string;
            from_storage: string;
            item: string;
            /** Format: date-time */
            time: string;
            to_container: string;
            to_storage: string;
            user: string;
        };
        /** @enum {string} */
        OrderState: "None" | "Good" | "Warning" | "Critical" | "Incoming";
        ShipmentCreateRequest: {
            /** Format: date-time */
            arrival_time: string;
            items: components["schemas"]["ShipmentItem"][];
        };
        ShipmentGetResponse: {
            id: string;
            items?: components["schemas"]["ShipmentItem"][] | null;
            /** Format: date-time */
            time_arive: string;
            /** Format: date-time */
            time_created: string;
        };
        ShipmentItem: {
            /** Format: float */
            amount: number;
            item: string;
        };
        /** @description An item with an amount lower than its order floor */
        ShortageItem: {
            /**
             * Format: float
             * @description The number of item currently in storage
             */
            amount: number;
            /**
             * Format: float
             * @description The number of items to buy to reach the order ceiling
             */
            amount_to_buy?: number | null;
            /** @description The name of the container where the item is stored */
            container: string;
            /** @description The items name */
            name: string;
            /** @description The name of the storage where the item is located */
            storage: string;
            /** @description The unit that the amount is measured in */
            unit?: string | null;
        };
        StateLog: {
            /** Format: float */
            amount: number;
            container: string;
            item: string;
            storage: string;
            /** Format: date-time */
            time: string;
            user: string;
        };
        /** @description Genaral info about the state of all storages */
        StatsGetResponse: {
            /**
             * Format: int64
             * @description The total number of items
             */
            items: number;
            /**
             * Format: int64
             * @description The total number of shortages
             */
            shortages: number;
            /**
             * Format: int64
             * @description The total number of suppliers
             */
            suppliers: number;
        };
        StockUpdate: {
            /**
             * Format: float
             * @description The number of items currently in storage
             */
            amount: number;
            /** @description The container where the item is stored */
            container: string;
            /** @description The items name */
            name: string;
            /** @description The storage where the item is located */
            storage: string;
        };
        /** @description Info used to take inventory */
        StockUpdateRequest: {
            /** @description List of items on which to update the amount */
            items: components["schemas"]["StockUpdate"][];
        };
        /** @description Info about a storage location */
        Storage: {
            inventory_interval?: null | components["schemas"]["Interval"];
            /** @description The suppliers name */
            name: string;
            /** @description If the storage require a read permission */
            protected: boolean;
        };
        /** @description Info used to create a storage location */
        StorageCreateRequest: {
            inventory_interval?: null | components["schemas"]["Interval"];
            /** @description The suppliers name */
            name: string;
            /** @description If the storage should require a read permission */
            protected: boolean;
        };
        /** @description Detailed information about where an item is stored */
        StorageListing: {
            /**
             * Format: float
             * @description The number of items currently in storage
             */
            amount: number;
            /** @description The container in which the item is stored */
            container: string;
            /**
             * Format: float
             * @description The order ceiling for this storage
             */
            max?: number | null;
            /**
             * Format: float
             * @description The order floor for this storage
             */
            min?: number | null;
            /**
             * Format: date-time
             * @description The next time the item is to be inventoried
             */
            next_inventory?: string | null;
            /** @description The state of the item (if more should be ordered) */
            state: components["schemas"]["OrderState"];
            /** @description The location where the item is stored */
            storage: string;
        };
        /** @description Info used to update a storage location */
        StorageUpdateRequest: {
            inventory_interval?: null | components["schemas"]["Interval"];
            /** @description The suppliers name */
            name: string;
            /** @description The new name of the storage if it is changed */
            new_name?: string | null;
            /** @description If the storage should require a read permission */
            protected: boolean;
        };
        /** @description Info used to update an item at a particular storage location */
        StoredUpdateRequest: {
            /**
             * Format: float
             * @description The current amount in storage
             */
            amount: number;
            /** @description The container the item is located in */
            container: string;
            /**
             * Format: float
             * @description The upper limit on the number of items (order ceiling)
             */
            max?: number | null;
            /**
             * Format: float
             * @description The lower limit on how many items should be in storage (order limit)
             */
            min?: number | null;
            /** @description The items name */
            name: string;
            /** @description The container to move the item to */
            new_container?: string | null;
            /** @description The storage to move the item to */
            new_storage?: string | null;
            /** @description The storage the item is located in */
            storage: string;
        };
        /** @description General info about a supplier */
        Supplier: {
            /** @description Hive group this supplier is assosiated with */
            group: string;
            /** @description Link to the suppliers website */
            link?: string | null;
            /** @description The suppliers name */
            name: string;
            /** @description Notes ex. order info */
            notes?: string | null;
            /** @description Password used to login to the suppliers website */
            password?: string | null;
            /** @description Username used to login to the suppliers website */
            username?: string | null;
        };
        /** @description Info used to add a supplier to an item */
        SupplierAddRequest: {
            /** @description Link to the item och the suppliers webshop */
            link?: string | null;
            /** @description The items name */
            name: string;
            /** @description If it is prefered to buy from this supplier instead of the others */
            prefered: boolean;
            /** @description The suppliers name */
            supplier: string;
        };
        /** @description Info used to create a supplier */
        SupplierCreateRequest: {
            /** @description Hive group this supplier is assosiated with */
            group: string;
            /** @description Link to the suppliers website */
            link?: string | null;
            /** @description The suppliers name */
            name: string;
            /** @description Notes ex. order info */
            notes?: string | null;
            /** @description Password used to login to the suppliers website */
            password?: string | null;
            /** @description Username used to login to the suppliers website */
            username?: string | null;
        };
        /** @description Information about the supplier of an item */
        SupplierListing: {
            /** @description A link to the item on the suppliers website */
            link?: string | null;
            /** @description The name of the supplier */
            name: string;
            /** @description If this is the prefered supplier of this item */
            prfered: boolean;
        };
        /** @description Info used to update a supplier */
        SupplierUpdateRequest: {
            /** @description Hive group this supplier should be assosiated with */
            group: string;
            /** @description Link to the suppliers website */
            link?: string | null;
            /** @description The name the supplier is supposed to have */
            name: string;
            /** @description Notes ex. order info */
            notes?: string | null;
            /** @description The name of the supplier before update (only if changeing) */
            old_name?: string | null;
            /** @description Password used to login to the suppliers website */
            password?: string | null;
            /** @description Username used to login to the suppliers website */
            username?: string | null;
        };
        UserInfo: {
            groups: components["schemas"]["Group"][];
            image: string;
            permissions: components["schemas"]["HivePermission"][];
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_container: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContainerCreateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    destroy_container: {
        parameters: {
            query: {
                /** @description The containers name */
                name: string;
                /** @description The name of the storage the container is at */
                storage: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_container: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContainerUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    move_container: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContainerMoveRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    items_due: {
        parameters: {
            query?: {
                /** @description The name of the storage to check */
                storage?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items due to be inventoried */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueStorage"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    take_stock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_item: {
        parameters: {
            query: {
                /** @description The items name */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item with detailed info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedItem"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_stored_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoredUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemAddRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_item: {
        parameters: {
            query: {
                /** @description The items name */
                name: string;
                /** @description The storage locations name */
                storage: string;
                /** @description The containers name */
                container: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemChangeNameRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    move_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemMoveRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_items: {
        parameters: {
            query?: {
                /** @description The items name */
                name?: string | null;
                /** @description The storages name */
                storage?: string | null;
                /** @description The containers name (requier storage to also be set) */
                container?: string | null;
                /** @description The suppliers name */
                supplier?: string | null;
                /** @description Atleast this many items should exist */
                min?: number | null;
                /** @description Atmost this many items should exist */
                max?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items with basic info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasicItem"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_log: {
        parameters: {
            query: {
                /** @description The name of the item */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of logs for an item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Log"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_shipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of orders with info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentGetResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShipmentCreateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    destroy: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_shortage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items with less than order floor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortageItem"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description General info about the entire organisation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsGetResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_storage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageCreateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    destroy_storage: {
        parameters: {
            query: {
                /** @description The storages name */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_storage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_storages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of storages with information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storage"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_storage_container_tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of storages with their containers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerStorage"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_container_item_tree_for_storage: {
        parameters: {
            query: {
                /** @description The name of the requested storage */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of storages with their containers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerItem"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_suppliers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of suppliers with info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_supplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_supplier: {
        parameters: {
            query: {
                /** @description The suppliers name */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_supplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    supply_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierAddRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unsupply_item: {
        parameters: {
            query: {
                /** @description The items name */
                name: string;
                /** @description The suppliers name */
                supplier: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Info about the currently logged in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OIDC callback function */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
